#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" -q -v/--verbose -p/--print/--print-values
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
# ...
echo "q: '${q}'"
echo "v: '${v}', verbose: '${verbose}'"
echo "p: '${p}', print: '${print}', print_values: '${print_values}'"
