#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" \
             -p/--password password \
             -u/--user user @validvalues=john,jeff,jack \
             --letters arg @@grep '^[a-z]$' @multivalue, \
             -- \
             "<file 1>" \
             "[<file 2>]" @@grep '^.*\.txt'
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_debug_dump() {
    # -p passw0rd --user jack --letters a,b,d,o memo.jpg memo.txt first second third
    #before export log_level=FINEST
    value 0 source_result parse_result process_result
    value passw0rd password
    empty p
    value jack user
    empty u
    arrayvalue letters a b d o
    value memo.jpg file_1
    value memo.txt file_2
    [ $# -eq 3 ]
    [ "$1" = first ]
    [ "$2" = second ]
    [ "$3" = third ]

    sa_debug_dump INFO
    sa_dump_option_values INFO
}
