#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" -u @@@ user
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_dummy_token() {
    # -u john first second
    value 0 source_result parse_result process_result
    value john user
    empty u
    [ $# -eq 2 ]
    [ "$1" = first ]
    [ "$2" = second ]
}
