#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" \
             --user user @varname=ssh_user
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_implicit_and_explicit_varname() {
    #
    value 0 source_result
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
}
