#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" \
             --text-file "*.txt" \
             -d/--data-file "*.dat" @multivalue
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_valid() {
    # --text-file text.txt -d data1.dat -d data2.dat
    value 0 source_result parse_result process_result
    value text.txt text_file
    arrayvalue d data1.dat data2.dat
    arrayvalue data_file data1.dat data2.dat
    [ $# -eq 0 ]
}

test_invalid1() {
    # --text-file text.atxt
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
}

test_invalid2() {
    # --data-file data1.data
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
}
