#!/usr/bin/env bash

export sa_use_cache=false
export log_level=ERROR

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] || { echo "ERROR: Failed to source simpleargs"; exit 1; }
script_path="$0"

###########################################

test_syntax_1() {
    #
    sa_parse "${script_path}" "<input file...>" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}

test_syntax_2() {
    #
    sa_parse "${script_path}" "[<input file...>]" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}

test_syntax_3() {
    #
    sa_parse "${script_path}" "[<input file>...]" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}

test_syntax_4() {
    #
    sa_parse "${script_path}" "<[input file]>" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}

test_syntax_5() {
    #
    sa_parse "${script_path}" "<[input file...]>" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}

test_syntax_6() {
    #
    sa_parse "${script_path}" "<[input file]...>" || parse_result="$?"
    value "${SA_PARSE_INVALID_ARGUMENTS}" parse_result
    grep --silent "Invalid syntax:" "${sa_test_stdout}"
    grep --silent "varargs optional:" "${sa_test_stdout}"
}
