#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?
[ "$source_result" -eq 0 ] &&
    sa_parse "$0" "<arg1>"; parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_no_arguments() {
    #
    value 0 source_result parse_result
    value "${SA_PROCESS_INVALID_ARGUMENTS}" process_result
}

test_one_positional_argument() {
    # first
    value 0 source_result parse_result process_result
    value first arg1
    [ $# -eq 0 ]
    [ -z "$1" ]
}

test_two_positional_arguments() {
    # first second
    value 0 source_result parse_result process_result
    value first arg1
    [ $# -eq 1 ]
    [ "$1" = second ]
    [ -z "$2" ]
}

test_positional_arguments_with_spaces() {
    # "first parameter" "and the second one" third "fourth with    more spaces"
    value 0 source_result parse_result process_result
    value "first parameter" arg1
    [ $# -eq 3 ]
    [ "$1" = "and the second one" ]
    [ "$2" = third ]
    [ "$3" = "fourth with    more spaces" ]
    [ -z "$4" ]
}

# No options defined, but option provided on command line -> fail
test_unknown_short_option() {
    # -u "parameter value"
    value 0 source_result parse_result
    value ${SA_PROCESS_GETOPT_FAILED} process_result
}

# No options defined, but option provided on command line -> fail
test_unknown_long_option() {
    # --user "parameter value"
    value 0 source_result parse_result
    value ${SA_PROCESS_GETOPT_FAILED} process_result
}

test_double_quotes_in_arguments() {
    # '"' "\"\""
    value 0 source_result parse_result process_result
    value '"' arg1
    [ $# -eq 1 ]
    echo "\$1: '$1'"
    [ "$1" = '""' ]
}

test_single_quotes_in_arguments() {
    # "'" "''"
    value 0 source_result parse_result process_result
    value "'" arg1
    [ $# -eq 1 ]
    [ "$1" = "''" ]
}

test_empty_argument() {
    # '' second
    value 0 source_result parse_result
    value $SA_PROCESS_VALIDATION_FAILED process_result
}
