#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" "[<input>]..." @@egrep '^[a-z0-9\. ]+$' "@default=input.txt"
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_no_args() {
    #
    value 0 source_result parse_result process_result
    arrayvalue input input.txt
}

test_one_arg() {
    # data.txt
    value 0 source_result parse_result process_result
    arrayvalue input data.txt
    [ $# -eq 0 ]
}

test_multiple_args() {
    # data1.txt data2.txt "third data.txt" data4.txt
    value 0 source_result parse_result process_result
    arrayvalue input data1.txt data2.txt "third data.txt" data4.txt
    [ $# -eq 0 ]
}

test_validation() {
    # data1.txt data2.txt "third-data@.txt" data4.txt
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
}
