#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" \
             --name @@grep "^a" @@grep "a$"
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_valid() {
    # --name amanda
    value 0 source_result parse_result process_result
    value amanda name
}

test_invalid() {
    # --name robert
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
    grep --silent "does not match regular expression '^a'" ${sa_test_stdout}
    grep --silent "does not match regular expression 'a$'" ${sa_test_stdout}
}

test_invalid_short_circuit() {
    # --name robert
    #before export _sa_short_circuit_validation=true
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
    grep --silent "does not match regular expression '^a'" ${sa_test_stdout}
    grep --silent "does not match regular expression 'a$'" ${sa_test_stdout} && false
}
