#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" \
             --port arg @@grep "^[1-9][0-9]*$" \
             @@@skiprest \
             --user arg @default=root \
             "<input file>"
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_valid() {
    # --port 8080
    value 0 source_result parse_result process_result
    value 8080 port
    empty user_default
    [ $# -eq 0 ]
}

test_invalid() {
    # --port 8080a
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
}

test_no_param() {
    # first-argument
    value 0 source_result parse_result process_result
    empty input_file
    [ $# -eq 1 ]
    [ "$1" = first-argument ]
}
