#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0"
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_empty_error() {
    #
    name=john
    empty name || true
}

test_array_length_different_error() {
    #
    a=( first second )
    arrayvalue a first second third || true
}

test_array_contents_different_error() {
    #
    a=( first second )
    arrayvalue a first wrong || true
}
