#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?
[ "$source_result" -eq 0 ] &&
    sa_parse "$0"
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_cannot_read_cache() {
    #
    #resetcache
    #before chmod a-rw ~/.simpleargs.d/cached/${test_file_basename}
    #after rm -f ~/.simpleargs.d/cached/${test_file_basename}
    value 0 source_result
    value "${SA_PARSE_CANNOT_READ_CACHE}" parse_result
}
