#!/usr/bin/env bash

######### Minimal example header #########
. ../target/simpleargs-bundle; source_result=$?

[ "$source_result" -eq 0 ] &&
    sa_parse "$0" "<input>..." @@egrep '^[a-z ]+$'
parse_result=$?
[ "$parse_result" -eq 0 ] &&
    sa_process "$@"; process_result=$?
[ "$process_result" -eq 0 ] &&
    eval "set -- ${sa_args}"
###########################################

test_no_args() {
    #
    value 0 source_result parse_result
    value "${SA_PROCESS_INVALID_ARGUMENTS}" process_result
}

test_one_arg() {
    # "first param"
    value 0 source_result parse_result process_result
    arrayvalue input "first param"
    [ $# -eq 0 ]
}

test_two_args() {
    # "first param" "second"
    value 0 source_result parse_result process_result
    arrayvalue input "first param" "second"
    [ $# -eq 0 ]
}

test_validation() {
    # "first param" "second" "this is in-valid@" "valid param"
    value 0 source_result parse_result
    value "${SA_PROCESS_VALIDATION_FAILED}" process_result
}
