#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" -f/--filter arg @multivalue @varname=filters \
              "<mp3 file>..." @varname=mp3s
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
# ...
echo "Filters:"
for filter in "${filters[@]}"; do
    echo " - ${filter}"
done
echo "MP3 files:"
for mp3 in "${mp3s[@]}"; do
    echo " - ${mp3}"
done
