#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0"
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------

log_level=INFO
# Simple logging using static log message
log INFO "Hello world!"
log INFO "Escape codes (\t\n) are printed as is!"
log INFO "%% <- two '%' signs"
log INFO "Format specifiers (%d, %s %.2f) are not interpreted."
name=Jim
log INFO "Include variables as usual if you like, ${name}!"
