#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" -v/--verbose @allowrepeat
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
# ...
case "${v_count}" in
    0) log_level=ERROR;;
    1) log_level=INFO;;
    *) log_level=DEBUG;;
esac
echo "-v flag given: ${v}(${verbose_count}): log level set to ${log_level}"
