#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" --user arg @default=root \
         "[<output>]" @default=stdout \
         "[<input file>]..." @default=-
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
# ...
echo "user: '${user}'"
echo "output: '${output}'"
echo "inputs:"
for i in "${input_file[@]}"
do
    echo "  - input: '${i}'"
done
