#!/usr/bin/env bash

# From man page of date:
# %w     day of week (0..6); 0 is Sunday
ci_actions='
  printf "analyse\ncompile\ntest\n"
  [ $(date +%w) -ne 5 ] && printf "deploy\n"
  true
'
# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" "<action>" @validvaluescommand="${ci_actions}"
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
echo "Executing action: ${action}"
