#!/usr/bin/env bash
sa_print_max_valid_values=5
# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" -e/--element arg @validvaluesfile=/tmp/elements.txt
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
# ...
echo "Your favourite chemical element: ${element}"
