#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }     #1
sa_parse "$0" --greeting arg "<person>"                                        #2
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"  #3
# ----------------------------------------------------------------------------
echo "${greeting}, ${person}!"                                                 #4
