#!/usr/bin/env bash

# -------------------------------- simpleargs --------------------------------
. "${SIMPLEARGS}" || { echo "Error loading '${SIMPLEARGS}'" >&2; exit 1; }
sa_parse "$0" "<output file>" "[<input files>]..."
sa_end_parse $?; sa_process "$@"; sa_end_process $?; eval "set -- ${sa_args}"
# ----------------------------------------------------------------------------
#...
> "${output_file}"
if [ ${#input_files[*]} -eq 0 ]
then
    # Read input from stdin
    sed 's/foo/bar/g' >> "${output_file}"
else
    for input_file in "${input_files[@]}"
    do
        echo "--- File: ${input_file} ---" >> "${output_file}"
        sed 's/foo/bar/g' "${input}" >> "${output_file}"
    done
fi
